### ISSUE TITLE
OpenStudio v1.0.0 Application Release Checklist

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudioApplication#91]
- [x] Create Debian, Darwin, and Windows untested build zips and upload to S3, Tim
- [X] Run simple model on all 3 platforms
- [x] Test and Release OpenStudio Measures, David, Eric
- [x] Run BEST tests with new installer, David?
- [x] Run Standards Tests with new installer, Matt?
- [x] Run hpxml tests with new installer, Scott?
- [x] Create Release Notes. API changes (if needed), Tim
- [x] Github tag and release, Tim
- [x] Upload packages to s3, Tim
- [x] Create using GitHub pages OpenstudioApplication.net, Tim
- [x] Update GitHub pages, Tim
- [x] Update App developer docs, Tim

**Iteration 1.0.0-rc-1 (4/1)**
Reported Issues
- RC1 OpenStudio application the bools in the apply measures now measure arguments still are stuck on true for mac.

**Comment by tijcolem** [comment]
OpenStudio Application v1.0.0 released. closing
